addons:
    apt:
        packages:
            - sshpass
language: java
sudo: false
install: mvn clean install
after_success:
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST rm app/*
    - sshpass -e scp -o StrictHostKeyChecking=no $TRAVIS_BUILD_DIR/target/spring-todomvc*shaded.jar $DEPLOY_USER@$DEPLOY_HOST:~/app
    - sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST java -jar app/spring-todomvc*shaded.jar



