addons:
    apt:
        packages:
            - sshpass
language: java
sudo: false
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean install
after_success:
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST rm app/*
    - sshpass -e scp $TRAVIS_BUILD_DIR/target/spring-todomvc*shaded.jar $DEPLOY_USER@$DEPLOY_HOST:~/app
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST java -jar ~/app/spring-todomvc*shaded.jar
    - sshpass -p $DEPLOY_PASS ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST touch file.txt
    - sshpass -p $DEPLOY_PASS ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST ls


